# fly.toml app configuration file generated for lingering-fog-3499 on 2023-08-22T21:23:27-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-fog-3499"
primary_region = "atl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
